routes/admin.php
<?php 

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;

// Forgot password
Route::get('admin/forgot-password', [AdminController::class, 'forgotPassword'])->name('admin.password.request');

// Send Mail
Route::post('admin/forgot-password', [AdminController::class, 'sendMail'])->name('admin.password.email');

// Reset Password
Route::get('admin/reset-password', [AdminController::class, 'resetPassword'])->name('admin.password.reset');

Route::post('admin/reset-password', [AdminController::class, 'updatePassword'])->name('admin.password.update');

Route::group(['middleware' => ['auth.admin'],'prefix' => 'admin', 'as' => 'admin.'], function() {
    
    Route::get('/', [ProductController::class, 'index'])->name('dashboard');

    // Get Form Login
    Route::get('login', [AdminController::class, 'login'])->name('login');

    // Check Login
    Route::post('login', [AdminController::class, 'checkLogin'])->name('check-login');

    // Logout
    Route::get('logout', [AdminController::class, 'logout'])->name('logout');


    // Get List Admin
    Route::get('index', [AdminController::class, 'index'])->name('index');

    // Get Form Create a Admin
    Route::get('create', [AdminController::class, 'create'])->name('create')->middleware('super.admin');

    // Add new Admin
    Route::post('store', [AdminController::class, 'store'])->name('store')->middleware('super.admin');

    // Show Admin
    Route::get('show/{id}', [AdminController::class, 'show'])->name('show')->middleware('super.admin');

    // Profile Admin
    Route::get('profile/{id}', [AdminController::class, 'profile'])->name('profile');

    // UpDate Admin
    Route::put('/{id}', [AdminController::class, 'update'])->name('update');

    // Route Orders
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'orders', 'as' => 'orders.'], function() {
        
        Route::get('/', [OrderController::class, 'index'])->name('index');
        Route::get('show/{id}', [OrderController::class, 'show'])->name('show');
        Route::put('update/{id}', [OrderController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [OrderController::class, 'destroy'])->name('destroy');

        // Get Form Order By Date
        Route::get('order-by-date', [OrderController::class, 'orderByDate'])->name('order-by-date');

        // Get List Order By Date
        Route::get('search-order-by-date', [OrderController::class, 'searchOrderByDate'])->name('search-order-by-date');

        // Get Credit Report
        Route::get('credit', [ReportController::class, 'creditReport'])->name('credit');

        // Get Summary Report
        Route::get('summary', [ReportController::class, 'summaryReport'])->name('summary');

        // Get Pending Order
        Route::get('pending', [OrderController::class, 'pendingOrder'])->name('pending');

        
    });

    // Route Users
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'users', 'as' => 'users.'], function() {

        // Get List Users
        Route::get('/', [UserController::class, 'index'])->name('index');

        // Get Profile
        Route::get('show/{id}', [UserController::class, 'show'])->name('show');

        // Get Form User By Date
        Route::get('user-by-date', [UserController::class, 'userByDate'])->name('user-by-date');

        // Get List Order By Date
        Route::get('search-user-by-date', [UserController::class, 'searchUserByDate'])->name('search-user-by-date');
    });

    // Route Category
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {

        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('create', [CategoryController::class, 'create'])->name('create');
        Route::post('/', [CategoryController::class, 'store'])->name('store');
        Route::get('show/{id}', [CategoryController::class, 'show'])->name('show');
        Route::get('edit/{id}', [CategoryController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [CategoryController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');   
    });

    // Route Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function() {

        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('create', [ProductController::class, 'create'])->name('create');
        Route::post('/', [ProductController::class, 'store'])->name('store');
        Route::get('show/{id}', [ProductController::class, 'show'])->name('show');
        Route::get('edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [ProductController::class, 'destroy'])->name('destroy');

        // Route::get('delete/{id}', function($id) {
        //     return redirect(route('admin.products.show', $id))->with('error', 'Sản Phẩm Hiện Đang Có Đơn Hàng');
        // });
    });
});

routes/web.php
<?php

use App\Http\Controllers\CartDemoController;
use App\Http\Controllers\ProductDemoController;
use App\Http\Controllers\SessionDemoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

require __DIR__.'/admin.php';

/**
 * Route For Session Demo
 */
Route::group(['prefix' => 'session-demo', 'as' => 'session-demo.'], function () {
    // URL này để hiển thị tất cả data đang có trong SESSION
    Route::get('/', [SessionDemoController::class, 'index'])->name('index');

    // URL này để thêm mới 1 sản phẩm vào Giỏ Hàng
    Route::post('/', [SessionDemoController::class, 'store'])->name('store');

    // URL này để update quantity của 1 sản phẩm đã có trong Giỏ Hàng
    Route::put('/{id}', [SessionDemoController::class, 'update'])->name('update');

    // URL này để xoá 1 sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/{id}', [SessionDemoController::class, 'destroy'])->name('destroy');

    // URL này để xoá tất cả sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/all', [SessionDemoController::class, 'destroyAll'])->name('destroyAll');
});

// Route for Product Demo
Route::get('product-demo', [ProductDemoController::class, 'index'])->name('product-demo.index')->middleware('guest');
Route::get('product-demo/create', [ProductDemoController::class, 'create'])->name('product-demo.create')->middleware('guest');
Route::post('product-demo', [ProductDemoController::class, 'store'])->name('product-demo.store')->middleware('guest');

// Route for Cart Demo
Route::group(['prefix' => 'cart-demo', 'as' => 'cart-demo.', 'middleware' => 'guest'], function () {
    Route::get('/', [CartDemoController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartDemoController::class, 'addCart'])->name('add-cart');
    Route::put('/{id}/update-quantity', [CartDemoController::class, 'updateQuantity'])->name('update-quantity');
    Route::delete('/{id}/remove-product-in-cart', [CartDemoController::class, 'removeProductInCart'])->name('remove-product-in-cart');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;

    use SoftDeletes;
    protected $fillable = [
        'admin_id',
        'category_id',
        'brand_id',
        'content',
        'thumbnail',
        'name',
        'quantity',
        'price',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function admin()
    {
        return $this->belongsTo(Admin::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function orderDetails()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function productImages()
    {
        return $this->hasMany(ProductImage::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Product;
use App\Models\ProductImage;
use App\Http\Requests\Admin\Product\StoreRequest;
use Illuminate\Support\Facades\Auth;
use App\Util\ProductCommon;

class ProductController extends Controller
{
    function __construct(Product $product)
    {

        $this->product = $product;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = [];
        
        $categories = Category::all();
        // dd($request->all());
        $products = $this->product->with('admin')->with('orderDetails')->orderBy('id', 'desc');

        if (!empty($request->search)) {
            $products->where('name', 'like', '%'.$request->search.'%');
        }
        if (!empty($request->category_id)) {
            $products->where('category_id', $request->category_id);
        }

        $products = $products->paginate(12);

        $data['categories'] = $categories;
        $data['products'] = $products;
        return view('backend.products.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];

        $categories = Category::all();
        $brands     = Brand::all();

        $data['brands']     = $brands;
        $data['categories'] = $categories;
        return view('backend.products.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        // Upload thumbnail
        $thumbnail = ProductCommon::uploadFile($request->thumbnail, 'product/thumbnail/');

        // Define Variable
        $product = [
            'admin_id' => Auth::guard('admin')->user()->id,
            'category_id' => $request->category_id,
            'brand_id' => $request->brand_id,
            'content' => $request->content,
            'thumbnail' => $thumbnail,
            'name' => $request->name,
            'quantity' => $request->quantity,
            'price' => $request->price,
        ];

        try {
            // Create product
           $product = Product::create($product);

           $product_images = ProductCommon::uploadMultipleFile($request->product_images, 'product/product_image/', $product->id);

           // Upload Multiple File
           foreach ($product_images as $product_image) {
               ProductImage::create($product_image);
           }
           
            // Success
            return redirect()->route('admin.products.index')
                ->with('success', 'Thêm mới sản phẩm thành công.');
        } catch (\Exception $ex) {
            return redirect()->back()
                ->with('error', $ex->getMessage())
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [];

        $product = Product::with('category')
        ->with('brand')
        ->with('admin')
        ->with('productImages')
        ->findOrFail($id);

        $data ['product'] = $product;
        return view('backend.products.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];

        $categories = Category::all();
        $brands     = Brand::all();

        $product = Product::with('category')
                    ->with('brand')
                    ->with('admin')
                    ->with('productImages')
                    ->findOrFail($id);

        $data ['product']   = $product;
        $data['brands']     = $brands;
        $data['categories'] = $categories;
        return view('backend.products.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Get Product
        $product = Product::with('category')
                    ->with('brand')
                    ->with('admin')
                    ->with('productImages')
                    ->findOrFail($id);

        $request->validate([
            'name' => 'required',
            'content' => 'required',
            'price' => 'required',
            'quantity' => 'required',
            'category_id' => 'required',
            'brand_id' => 'required',
        ]);

        // Xóa Product Image
        if (!empty($request->check_images)) {
            $product_images = ProductImage::where('product_id', $product->id)->whereNotIn('id', $request->check_images)->get();
            foreach ($product_images as $product_image) {
                ProductCommon::removeFile($product_image->url);

                ProductImage::destroy($product_image->id);
            }    
        }else{
            $product_images = ProductImage::where('product_id', $product->id)->get();
            foreach ($product_images as $product_image) {
                ProductCommon::removeFile($product_image->url);

                ProductImage::destroy($product_image->id);
            }
        }
        
        // Upload Product Image
        if (!empty($request->product_images)) {
            $product_images = ProductCommon::uploadMultipleFile($request->product_images, 'product/product_image/', $product->id);

           // Upload Multiple File
           foreach ($product_images as $product_image) {
               ProductImage::create($product_image);
           }
        }

        if (!empty($request->thumbnail)) {
            ProductCommon::removeFile($product->thumbnail);
            $product->thumbnail = ProductCommon::uploadFile($request->thumbnail, 'product/thumbnail/');
        }

        $product->name = $request->name;
        $product->content = $request->content;
        $product->price = $request->price;
        $product->quantity = $request->quantity;
        $product->category_id = $request->category_id;
        $product->brand_id = $request->brand_id;

        try {
            $product->save();

            return redirect(route('admin.products.show', $product->id))->with('success', 'Cập Nhật Sản Phẩm Thành Công');
        } catch (Exception $e) {
            return back()->with('error', 'Cập Nhật Sản Phẩm Không Thành Công');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->product->with('orderDetails')
            ->findOrFail($id);

        if (count($product->orderDetails) === 0) {
            try {
                $product_images = ProductImage::where('product_id', $product->id)->get();
                foreach ($product_images as $product_image) {
                    ProductCommon::removeFile($product_image->url);

                    ProductImage::destroy($product_image->id);
                }

                ProductCommon::removeFile($product->thumbnail);
                // Delete data of table products
                $product->delete();

                // Success
                return redirect()->route('admin.products.index')
                    ->with('success', 'Xóa Thành Công Sản Phẩm');
            } catch (\Exception $ex) {
                return redirect()->back()
                    ->with('error', $ex->getMessage());
            }
        }else{
            return redirect(route('admin.products.show', $product->id))->with('error', 'Sản Phẩm Hiện Đang Có Đơn Hàng');
        }

        
    }
}

resources/views/backend/products/create.blade.php
@extends('backend.layouts.master')

@section('title', 'Thêm Mới Sản Phẩm')

@section('content')

    <form action="{{ route('admin.products.store') }}" method="post" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            
            <div class="card-body">
              <div class="form-group">
                <label for="inputName">Tên Sản Phẩm<span class="text-danger">(*)</span></label>
                <input type="text" name="name" id="inputName" value="{{ old('name') }}" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputDescription">Mô Tả Sản Phẩm<span class="text-danger">(*)</span></label>
                <textarea id="inputDescription" name="content" class="form-control" rows="4"></textarea>
              </div>
              <div class="form-group">
                <label for="inputDescription">Loại Sản Phẩm<span class="text-danger">(*)</span></label>
                @foreach ($categories as $category)
                <div class="form-check">
                  <input class="form-check-input" type="radio" value="{{ $category->id }}" name="category_id">
                  <label class="form-check-label">{{ $category->name }}</label>
                </div>
                @endforeach
              </div>
              <div class="form-group">
                <label for="inputDescription">Thương Hiệu Sản Phẩm<span class="text-danger">(*)</span></label>
                @foreach ($brands as $brand)
                <div class="form-check">
                  <input class="form-check-input" type="radio" value="{{ $brand->id }}" name="brand_id">
                  <label class="form-check-label">{{ $brand->name }}</label>
                </div>
                @endforeach
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <div class="col-md-6">
          <div class="card card-secondary">
            <div class="card-body">
              <div class="form-group">
                <label for="inputClientCompany">Hình Đại Diện Sản Phẩm<span class="text-danger">(*)</span></label>
                <div class="custom-file">
                  <input type="file" name="thumbnail" class="custom-file-input" id="customFile">
                  <label class="custom-file-label">Choose file</label>
                </div>
              </div>
              <div class="form-group">
                <label for="inputProjectLeader">Hình Ảnh Sản Phẩm<span class="text-danger">(*)</span></label>
                <div class="custom-file">
                  <input type="file" name="product_images[]" class="custom-file-input" id="customFile" multiple>
                  <label class="custom-file-label">Choose file</label>
                </div>
              </div>
              <div class="form-group">
                <label for="inputSpentBudget">Số Lượng Sản Phẩm<span class="text-danger">(*)</span></label>
                <input type="number" value="{{ old('quantity') }}" name="quantity" id="inputSpentBudget" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputEstimatedDuration">Giá Sản Phẩm<span class="text-danger">(*)</span></label>
                <input type="number" value="{{ old('price') }}" name="price" id="inputEstimatedDuration" class="form-control">
              </div>
              <p><i><span class="text-danger">(*)</span> Phải Điền Vào Trường Này</i></p>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <a href="{{ route('admin.products.create') }}" class="btn btn-secondary">Đặt Lại</a>
          <input type="submit" value="Tạo Sản Phẩm" class="btn btn-success float-right">
        </div>
      </div>
    </form>
@endsection

@push('js')
  

<!-- bs-custom-file-input -->
<script src="{{ asset('backend/admin_lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
</script>
@endpush

resources/views/backend/products/edit.blade.php
@extends('backend.layouts.master')

@section('title', 'Cập Nhật Sản Phẩm')

@section('content')

    <form action="{{ route('admin.products.update', $product->id) }}" method="post" enctype="multipart/form-data">
      @csrf
      @method('put')
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            
            <div class="card-body">
              <div class="form-group">
                <label for="inputName">Tên Sản Phẩm<span class="text-danger">(*)</span></label>
                <input type="text" name="name" id="inputName" value="{{ $product->name }}" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputDescription">Mô Tả Sản Phẩm<span class="text-danger">(*)</span></label>
                <textarea id="inputDescription" value="{{ $product->content }}" name="content" class="form-control" rows="4">{{ $product->content }}</textarea>
              </div>
              <div class="form-group">
                <label for="inputDescription">Loại Sản Phẩm<span class="text-danger">(*)</span></label>
                @foreach ($categories as $category)
                <div class="form-check">
                  <input class="form-check-input" type="radio" value="{{ $category->id }}" name="category_id" {{ $product->category_id == $category->id ? 'checked' : ''}}>
                  <label class="form-check-label">{{ $category->name }}</label>
                </div>
                @endforeach
              </div>
              <div class="form-group">
                <label for="inputDescription">Thương Hiệu Sản Phẩm<span class="text-danger">(*)</span></label>
                @foreach ($brands as $brand)
                <div class="form-check">
                  <input class="form-check-input" type="radio" value="{{ $brand->id }}" name="brand_id" {{ $product->brand_id == $brand->id ? 'checked' : ''}}>
                  <label class="form-check-label">{{ $brand->name }}</label>
                </div>
                @endforeach
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <div class="col-md-6">
          <div class="card card-secondary">
            <div class="card-body">
              <div class="form-group">
                <label for="inputClientCompany">Hình Đại Diện Sản Phẩm<span class="text-danger">(*)</span></label>
                <div class="custom-file">
                  <input type="file" name="thumbnail" class="custom-file-input" id="customFile">
                  <label class="custom-file-label">Choose file</label>
                </div>
                <img src="{{asset($product->thumbnail)}}" alt="{{ $product->name }}" style="width: 100%;">
              </div>
              <div class="form-group">
                <label for="inputProjectLeader">Hình Ảnh Sản Phẩm<span class="text-danger">(*)</span></label>
                <div class="custom-file" style="margin-bottom: 5px;">
                  <input type="file" name="product_images[]" class="custom-file-input" id="customFile" multiple>
                  <label class="custom-file-label">Choose file</label>
                </div>
                @foreach ($product->productImages as $productImage)
                  <input class="form-check-input" value="{{ $productImage->id }}" name="check_images[]" type="checkbox" style="margin-left: 0%;" checked>
                  <img src="{{asset($productImage->url)}}" style="width: 20%; margin-right: 6%; border: 1px solid red;">
                @endforeach
              </div>
              <div class="form-group">
                <label for="inputSpentBudget">Số Lượng Sản Phẩm<span class="text-danger">(*)</span></label>
                <input type="number" value="{{ $product->quantity }}" name="quantity" id="inputSpentBudget" class="form-control">
              </div>
              <div class="form-group">
                <label for="inputEstimatedDuration">Giá Sản Phẩm<span class="text-danger">(*)</span></label>
                <input type="number" value="{{ $product->price }}" name="price" id="inputEstimatedDuration" class="form-control">
              </div>
              <p><i><span class="text-danger">(*)</span> Phải Điền Vào Trường Này</i></p>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <input type="submit" value="Cập Nhật Sản Phẩm" class="btn btn-success float-right">
        </div>
      </div>
    </form>
@endsection

@push('js')
  

<!-- bs-custom-file-input -->
<script src="{{ asset('backend/admin_lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
<!-- Page specific script -->
<script>
$(function () {
  bsCustomFileInput.init();
});
</script>
@endpush

resources/views/backend/products/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Danh Sách Sản Phẩm')

@section('content')
@if (!empty($products))
  @if ( Route::currentRouteName() === 'admin.products.index')
    <div class="card card-danger">
      <div class="card-header">
        <h3 class="card-title">Tìm Sản Phẩm</h3>
      </div>
      <div class="card-body">
        <form action="">
        <div class="row">
          <div class="col-4">
            <input type="text" name="search" value="{{ old('search') }}" class="form-control" placeholder="Tên Sản Phẩm">
          </div>
          <div class="col-4">
            <select class="form-control select2 select2-hidden-accessible" name="category_id" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
              <option selected="selected" data-select2-id="3">Lựa Chọn Danh Mục</option>
              @foreach ($categories as $category)                 
              <option value="{{ $category->id }}">{{ $category->name }}</option>

              @endforeach
            </select>
          </div>
          <div class="col-4">
            <button type="submit" value="Tìm Sản Phẩm" class="btn btn-success float-left">Tìm Sản Phẩm</button> |
            <a href="{{ route('admin.products.index') }}" class="btn btn-secondary">Đặt Lại</a>
          </div>
        </div>
        </form>
      </div>
      <!-- /.card-body -->
    </div>
  @endif
	<div class="card card-solid">
        <div class="card-body pb-0">
          <div class="row">
          	@foreach ($products as $product)

            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
              <div class="card bg-light d-flex flex-fill">
                <div class="card-header text-muted border-bottom-0">
                </div>
                <div class="card-body pt-0">
                  <div class="row">	
                    <div class="col-7">
                      <h2 class="lead"><b>{{ $product->name }}</b></h2>
                      <p class="text-muted text-sm"><b>Số lượng: </b>{{ $product->quantity }}</p>
                      <p class="text-muted text-sm"><b>Giá: </b>{{ $product->price }} </p>
                      <p class="text-muted text-sm"><b>Admin: </b>{{ $product->admin->name }}</p>
                      <p class="text-muted text-sm"><b>Số đơn hàng: </b>{{ count($product->orderDetails) }}</p>
                    </div>
                    <div class="col-5 text-center">
                      <img src="{{ asset($product->thumbnail) }}" class="img-circle img-fluid">
                    </div>
                  </div>
                </div>
                <div class="card-footer">
                  <div class="text-right btn-group">
                    <a href="{{ route('admin.products.show', $product->id) }}" class="btn btn-sm btn-primary">Chi Tiết
                    </a>
                    <a href="{{ route('admin.products.edit', $product->id) }}" class="btn btn-sm btn-info">Cập Nhật
                    </a>
                    <form action="{{ route('admin.products.destroy', $product->id ) }}" method="post">
                      @csrf
                      @method('delete')
                      <button type="submit" class="btn btn-sm btn-danger" {{count($product->orderDetails) > 0 ? 'disabled' : ''}}>Xóa</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>

            @endforeach

          </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          <nav aria-label="Contacts Page Navigation">
            <ul class="pagination justify-content-center m-0">
              {{ $products->links('pagination::bootstrap-4') }}
            </ul>

          </nav>
        </div>
        <!-- /.card-footer -->
      </div>
@endif
@endsection