routes/admin.php
<?php 

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;

// Forgot password
Route::get('admin/forgot-password', [AdminController::class, 'forgotPassword'])->name('admin.password.request');

// Send Mail
Route::post('admin/forgot-password', [AdminController::class, 'sendMail'])->name('admin.password.email');

// Reset Password
Route::get('admin/reset-password', [AdminController::class, 'resetPassword'])->name('admin.password.reset');

Route::post('admin/reset-password', [AdminController::class, 'updatePassword'])->name('admin.password.update');

Route::group(['middleware' => ['auth.admin'],'prefix' => 'admin', 'as' => 'admin.'], function() {
    
    Route::get('/', [ProductController::class, 'index'])->name('dashboard');

    // Get Form Login
    Route::get('login', [AdminController::class, 'login'])->name('login');

    // Check Login
    Route::post('login', [AdminController::class, 'checkLogin'])->name('check-login');

    // Logout
    Route::get('logout', [AdminController::class, 'logout'])->name('logout');


    // Get List Admin
    Route::get('index', [AdminController::class, 'index'])->name('index');

    // Get Form Create a Admin
    Route::get('create', [AdminController::class, 'create'])->name('create')->middleware('super.admin');

    // Add new Admin
    Route::post('store', [AdminController::class, 'store'])->name('store')->middleware('super.admin');

    // Show Admin
    Route::get('show/{id}', [AdminController::class, 'show'])->name('show')->middleware('super.admin');

    // Profile Admin
    Route::get('profile/{id}', [AdminController::class, 'profile'])->name('profile');

    // UpDate Admin
    Route::put('/{id}', [AdminController::class, 'update'])->name('update');

    // Route Orders
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'orders', 'as' => 'orders.'], function() {
        
        Route::get('/', [OrderController::class, 'index'])->name('index');
        Route::get('show/{id}', [OrderController::class, 'show'])->name('show');
        Route::put('update/{id}', [OrderController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [OrderController::class, 'destroy'])->name('destroy');

        // Get Form Order By Date
        Route::get('order-by-date', [OrderController::class, 'orderByDate'])->name('order-by-date');

        // Get List Order By Date
        Route::get('search-order-by-date', [OrderController::class, 'searchOrderByDate'])->name('search-order-by-date');

        // Get Credit Report
        Route::get('credit', [ReportController::class, 'creditReport'])->name('credit');

        // Get Summary Report
        Route::get('summary', [ReportController::class, 'summaryReport'])->name('summary');

        // Get Pending Order
        Route::get('pending', [OrderController::class, 'pendingOrder'])->name('pending');

        
    });

    // Route Users
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'users', 'as' => 'users.'], function() {

        // Get List Users
        Route::get('/', [UserController::class, 'index'])->name('index');

        // Get Profile
        Route::get('show/{id}', [UserController::class, 'show'])->name('show');

        // Get Form User By Date
        Route::get('user-by-date', [UserController::class, 'userByDate'])->name('user-by-date');

        // Get List Order By Date
        Route::get('search-user-by-date', [UserController::class, 'searchUserByDate'])->name('search-user-by-date');
    });

    // Route Category
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {

        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('create', [CategoryController::class, 'create'])->name('create');
        Route::post('/', [CategoryController::class, 'store'])->name('store');
        Route::get('show/{id}', [CategoryController::class, 'show'])->name('show');
        Route::get('edit/{id}', [CategoryController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [CategoryController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');   
    });

    // Route Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function() {

        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('create', [ProductController::class, 'create'])->name('create');
        Route::post('/', [ProductController::class, 'store'])->name('store');
        Route::get('show/{id}', [ProductController::class, 'show'])->name('show');
        Route::get('edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [ProductController::class, 'destroy'])->name('destroy');

        // Route::get('delete/{id}', function($id) {
        //     return redirect(route('admin.products.show', $id))->with('error', 'Sản Phẩm Hiện Đang Có Đơn Hàng');
        // });
    });
});

routes/web.php
<?php

use App\Http\Controllers\CartDemoController;
use App\Http\Controllers\ProductDemoController;
use App\Http\Controllers\SessionDemoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

require __DIR__.'/admin.php';

/**
 * Route For Session Demo
 */
Route::group(['prefix' => 'session-demo', 'as' => 'session-demo.'], function () {
    // URL này để hiển thị tất cả data đang có trong SESSION
    Route::get('/', [SessionDemoController::class, 'index'])->name('index');

    // URL này để thêm mới 1 sản phẩm vào Giỏ Hàng
    Route::post('/', [SessionDemoController::class, 'store'])->name('store');

    // URL này để update quantity của 1 sản phẩm đã có trong Giỏ Hàng
    Route::put('/{id}', [SessionDemoController::class, 'update'])->name('update');

    // URL này để xoá 1 sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/{id}', [SessionDemoController::class, 'destroy'])->name('destroy');

    // URL này để xoá tất cả sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/all', [SessionDemoController::class, 'destroyAll'])->name('destroyAll');
});

// Route for Product Demo
Route::get('product-demo', [ProductDemoController::class, 'index'])->name('product-demo.index')->middleware('guest');
Route::get('product-demo/create', [ProductDemoController::class, 'create'])->name('product-demo.create')->middleware('guest');
Route::post('product-demo', [ProductDemoController::class, 'store'])->name('product-demo.store')->middleware('guest');

// Route for Cart Demo
Route::group(['prefix' => 'cart-demo', 'as' => 'cart-demo.', 'middleware' => 'guest'], function () {
    Route::get('/', [CartDemoController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartDemoController::class, 'addCart'])->name('add-cart');
    Route::put('/{id}/update-quantity', [CartDemoController::class, 'updateQuantity'])->name('update-quantity');
    Route::delete('/{id}/remove-product-in-cart', [CartDemoController::class, 'removeProductInCart'])->name('remove-product-in-cart');
});

resources/views/backend/layouts/css.blade.php
<!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/dist/css/adminlte.min.css') }}">

  @stack('css')

resources/views/backend/layouts/footer.blade.php
<!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

resources/views/backend/layouts/header.blade.php
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">@yield('title')</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Trang Chủ</a></li>
              <li class="breadcrumb-item active">@yield('title')</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

resources/views/backend/layouts/js.blade.php
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('backend/admin_lte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('backend/admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/admin_lte/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('backend/admin_lte/dist/js/demo.js') }}"></script>

@stack('js')

<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date picker
    $('#reservationdate').datetimepicker({
        format: 'L'
    });

    //Date and time picker
    $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datetimepicker({
      format: 'LT'
    })

    //Bootstrap Duallistbox
    $('.duallistbox').bootstrapDualListbox()

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    $('.my-colorpicker2').on('colorpickerChange', function(event) {
      $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
    })

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    })

  })
  // BS-Stepper Init
  document.addEventListener('DOMContentLoaded', function () {
    window.stepper = new Stepper(document.querySelector('.bs-stepper'))
  })

  // DropzoneJS Demo Code Start
  Dropzone.autoDiscover = false

  // Get the template HTML and remove it from the doumenthe template HTML and remove it from the doument
  var previewNode = document.querySelector("#template")
  previewNode.id = ""
  var previewTemplate = previewNode.parentNode.innerHTML
  previewNode.parentNode.removeChild(previewNode)

  var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
    url: "/target-url", // Set the url
    thumbnailWidth: 80,
    thumbnailHeight: 80,
    parallelUploads: 20,
    previewTemplate: previewTemplate,
    autoQueue: false, // Make sure the files aren't queued until manually added
    previewsContainer: "#previews", // Define the container to display the previews
    clickable: ".fileinput-button" // Define the element that should be used as click trigger to select files.
  })

  myDropzone.on("addedfile", function(file) {
    // Hookup the start button
    file.previewElement.querySelector(".start").onclick = function() { myDropzone.enqueueFile(file) }
  })

  // Update the total progress bar
  myDropzone.on("totaluploadprogress", function(progress) {
    document.querySelector("#total-progress .progress-bar").style.width = progress + "%"
  })

  myDropzone.on("sending", function(file) {
    // Show the total progress bar when upload starts
    document.querySelector("#total-progress").style.opacity = "1"
    // And disable the start button
    file.previewElement.querySelector(".start").setAttribute("disabled", "disabled")
  })

  // Hide the total progress bar when nothing's uploading anymore
  myDropzone.on("queuecomplete", function(progress) {
    document.querySelector("#total-progress").style.opacity = "0"
  })

  // Setup the buttons for all transfers
  // The "add files" button doesn't need to be setup because the config
  // `clickable` has already been specified.
  document.querySelector("#actions .start").onclick = function() {
    myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED))
  }
  document.querySelector("#actions .cancel").onclick = function() {
    myDropzone.removeAllFiles(true)
  }
  // DropzoneJS Demo Code End
</script>

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <title>@yield('title', 'Dashboard')</title>
    {{-- css --}}
    @include('backend.layouts.css')
</head>
<body class="hold-transition layout-top-nav">
    <div class="wrapper">
    
    {{-- navbar --}}
    @include('backend.layouts.navbar')

    {{-- header --}}
    @include('backend.layouts.header')

    <!-- Main content -->
    <div class="content">
      <div class="container">
            @yield('content')
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

    {{-- footer --}}
    @include('backend.layouts.footer')
</div>
    {{-- js --}}
    @include('backend.layouts.js')
</body>
</html>

resources/views/backend/layouts/navbar.blade.php
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
      <a href="{{ route('admin.dashboard') }}" class="navbar-brand">
        <img src="{{asset('backend/admin_lte/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      </a>

      <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{{ route('admin.dashboard') }}" class="nav-link">Trang Chủ</a>
          </li>
    @if (auth('admin')->user()->role_id == 1 || auth('admin')->user()->role_id == 2)
          
	         <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Đơn Hàng</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
              	<li><a href="{{ route('admin.orders.index') }}" class="dropdown-item">Danh Sách Đơn Hàng</a></li>
              	<li><a href="{{ route('admin.orders.order-by-date') }}" class="dropdown-item">Đơn Hàng Theo Ngày</a></li>
            		<li><a href="{{ route('admin.orders.pending') }}" class="dropdown-item">Đơn Hàng Chưa Xử Lý</a></li>
            		<li><a href="{{ route('admin.orders.credit') }}" class="dropdown-item">Báo Cáo Tài Chính</a></li>
            		<li><a href="{{ route('admin.orders.summary') }}" class="dropdown-item">Báo Cáo Tóm Tắt Đơn Hàng</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Khách Hàng</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li><a href="{{ route('admin.users.index') }}" class="dropdown-item">Danh Sách Khách Hàng</a></li>
                <li><a href="{{ route('admin.users.user-by-date') }}" class="dropdown-item">Khách Hàng Theo Ngày</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Danh Mục</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li><a href="{{ route('admin.categories.index') }}" class="dropdown-item">Danh Sách Danh Mục</a></li>
                <li><a href="{{ route('admin.categories.create') }}" class="dropdown-item">Tạo Danh Mục</a></li>
            </ul>
          </li>
        @if (auth('admin')->user()->role_id == 1)
          
          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Quản trị viên</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li><a href="{{ route('admin.index') }}" class="dropdown-item">Danh Sách Quản trị Viên</a></li>
                <li><a href="{{ route('admin.create') }}" class="dropdown-item">Tạo Quản Trị Viên</a></li>
            </ul>
          </li>
        @endif
    @endif
          <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Sản Phẩm</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li><a href="{{ route('admin.products.index') }}" class="dropdown-item">Danh Sách Sản Phẩm</a></li>
                <li><a href="{{ route('admin.products.create') }}" class="dropdown-item">Tạo Sản Phẩm</a></li>
            </ul>
          </li>
        </ul>

        <!-- SEARCH FORM -->
        <form method="get" action="{{ route('admin.products.index') }}" class="form-inline ml-0 ml-md-3">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" name="search" placeholder="Nhập tên sản phẩm" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>
      </div>

      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">{{ auth('admin')->user()->name }}</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                <li><a href="{{ route('admin.profile', ['id' => auth('admin')->user()->id]) }}" class="dropdown-item">Profile</a></li>
                <li><a href="{{ route('admin.logout') }}" class="dropdown-item">Đăng Xuất</a></li>
            </ul>
          </li>
      </ul>
    </div>
  </nav>
  <!-- /.navbar -->