routes/admin.php
<?php 

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;

// Forgot password
Route::get('admin/forgot-password', [AdminController::class, 'forgotPassword'])->name('admin.password.request');

// Send Mail
Route::post('admin/forgot-password', [AdminController::class, 'sendMail'])->name('admin.password.email');

// Reset Password
Route::get('admin/reset-password', [AdminController::class, 'resetPassword'])->name('admin.password.reset');

Route::post('admin/reset-password', [AdminController::class, 'updatePassword'])->name('admin.password.update');

Route::group(['middleware' => ['auth.admin'],'prefix' => 'admin', 'as' => 'admin.'], function() {
    
    Route::get('/', [ProductController::class, 'index'])->name('dashboard');

    // Get Form Login
    Route::get('login', [AdminController::class, 'login'])->name('login');

    // Check Login
    Route::post('login', [AdminController::class, 'checkLogin'])->name('check-login');

    // Logout
    Route::get('logout', [AdminController::class, 'logout'])->name('logout');


    // Get List Admin
    Route::get('index', [AdminController::class, 'index'])->name('index');

    // Get Form Create a Admin
    Route::get('create', [AdminController::class, 'create'])->name('create')->middleware('super.admin');

    // Add new Admin
    Route::post('store', [AdminController::class, 'store'])->name('store')->middleware('super.admin');

    // Show Admin
    Route::get('show/{id}', [AdminController::class, 'show'])->name('show')->middleware('super.admin');

    // Profile Admin
    Route::get('profile/{id}', [AdminController::class, 'profile'])->name('profile');

    // UpDate Admin
    Route::put('/{id}', [AdminController::class, 'update'])->name('update');

    // Route Orders
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'orders', 'as' => 'orders.'], function() {
        
        Route::get('/', [OrderController::class, 'index'])->name('index');
        Route::get('show/{id}', [OrderController::class, 'show'])->name('show');
        Route::put('update/{id}', [OrderController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [OrderController::class, 'destroy'])->name('destroy');

        // Get Form Order By Date
        Route::get('order-by-date', [OrderController::class, 'orderByDate'])->name('order-by-date');

        // Get List Order By Date
        Route::get('search-order-by-date', [OrderController::class, 'searchOrderByDate'])->name('search-order-by-date');

        // Get Credit Report
        Route::get('credit', [ReportController::class, 'creditReport'])->name('credit');

        // Get Summary Report
        Route::get('summary', [ReportController::class, 'summaryReport'])->name('summary');

        // Get Pending Order
        Route::get('pending', [OrderController::class, 'pendingOrder'])->name('pending');

        
    });

    // Route Users
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'users', 'as' => 'users.'], function() {

        // Get List Users
        Route::get('/', [UserController::class, 'index'])->name('index');

        // Get Profile
        Route::get('show/{id}', [UserController::class, 'show'])->name('show');

        // Get Form User By Date
        Route::get('user-by-date', [UserController::class, 'userByDate'])->name('user-by-date');

        // Get List Order By Date
        Route::get('search-user-by-date', [UserController::class, 'searchUserByDate'])->name('search-user-by-date');
    });

    // Route Category
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {

        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('create', [CategoryController::class, 'create'])->name('create');
        Route::post('/', [CategoryController::class, 'store'])->name('store');
        Route::get('show/{id}', [CategoryController::class, 'show'])->name('show');
        Route::get('edit/{id}', [CategoryController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [CategoryController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');   
    });

    // Route Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function() {

        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('create', [ProductController::class, 'create'])->name('create');
        Route::post('/', [ProductController::class, 'store'])->name('store');
        Route::get('show/{id}', [ProductController::class, 'show'])->name('show');
        Route::get('edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [ProductController::class, 'destroy'])->name('destroy');

        // Route::get('delete/{id}', function($id) {
        //     return redirect(route('admin.products.show', $id))->with('error', 'Sản Phẩm Hiện Đang Có Đơn Hàng');
        // });
    });
});

routes/web.php
<?php

use App\Http\Controllers\CartDemoController;
use App\Http\Controllers\ProductDemoController;
use App\Http\Controllers\SessionDemoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

require __DIR__.'/admin.php';

/**
 * Route For Session Demo
 */
Route::group(['prefix' => 'session-demo', 'as' => 'session-demo.'], function () {
    // URL này để hiển thị tất cả data đang có trong SESSION
    Route::get('/', [SessionDemoController::class, 'index'])->name('index');

    // URL này để thêm mới 1 sản phẩm vào Giỏ Hàng
    Route::post('/', [SessionDemoController::class, 'store'])->name('store');

    // URL này để update quantity của 1 sản phẩm đã có trong Giỏ Hàng
    Route::put('/{id}', [SessionDemoController::class, 'update'])->name('update');

    // URL này để xoá 1 sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/{id}', [SessionDemoController::class, 'destroy'])->name('destroy');

    // URL này để xoá tất cả sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/all', [SessionDemoController::class, 'destroyAll'])->name('destroyAll');
});

// Route for Product Demo
Route::get('product-demo', [ProductDemoController::class, 'index'])->name('product-demo.index')->middleware('guest');
Route::get('product-demo/create', [ProductDemoController::class, 'create'])->name('product-demo.create')->middleware('guest');
Route::post('product-demo', [ProductDemoController::class, 'store'])->name('product-demo.store')->middleware('guest');

// Route for Cart Demo
Route::group(['prefix' => 'cart-demo', 'as' => 'cart-demo.', 'middleware' => 'guest'], function () {
    Route::get('/', [CartDemoController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartDemoController::class, 'addCart'])->name('add-cart');
    Route::put('/{id}/update-quantity', [CartDemoController::class, 'updateQuantity'])->name('update-quantity');
    Route::delete('/{id}/remove-product-in-cart', [CartDemoController::class, 'removeProductInCart'])->name('remove-product-in-cart');
});

resources/views/backend/admins/create.blade.php
@extends('backend.layouts.master')

@section('title', 'Tạo Mới Quản Trị Viên')

@section('content')

<div class="card">
  <div class="card-body register-card-body">
    <p class="login-box-msg">Tạo Mới Admin</p>
    <form action="{{ route('admin.store') }}" method="post">
  @csrf
      <div class="form-group">
        <label for="inputSpentBudget">Tên Quản Trị Viên<span class="text-danger">(*)</span></label>
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="name" placeholder="Nhập Tên" value="{{ old('name') }}">
          <div class="input-group-append">
            <div class="input-group-text">
        @error('name')
        		  <span class="text-danger">{{ $message }}</span>
        @enderror
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="inputSpentBudget">Email Quản Trị Viên<span class="text-danger">(*)</span></label>
        <div class="input-group mb-3">
          <input type="email" class="form-control" name="email" placeholder="Nhập Email" value="{{ old('email') }}">
          <div class="input-group-append">
            <div class="input-group-text">
          @error('email')
        		  <span class="text-danger">{{ $message }}</span>
        	@enderror
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="inputSpentBudget">Số Điện Thoại<span class="text-danger">(*)</span></label>
        <div class="input-group mb-3">
          <input type="number" class="form-control" name="phone" placeholder="Nhập Số Điện Thoại" value="{{ old('phone') }}">
          <div class="input-group-append">
            <div class="input-group-text">
          @error('phone')
        			<span class="text-danger">{{ $message }}</span>
        	@enderror
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="inputSpentBudget">Chỉ Định Quyền<span class="text-danger">(*)</span></label>
        <select class="form-control" name="role">
          <option selected="selected" data-select2-id="3"></option>
        @foreach ($roles as $role)
          @continue($role->id == 1)
            <option value="{{ $role->id }}">{{ $role->role }}</option>
        @endforeach
        </select>
        @error('role')
          <div class="text-danger">{{ $message }}</div>
        @enderror
      </div>
      <div class="form-group">
        <label for="inputSpentBudget">Có Thể Sử Dụng<span class="text-danger">(*)</span></label>
        <div class="custom-control custom-radio">
          <input class="custom-control-input" type="radio" id="customRadio1" name="status" value="1">
          <label for="customRadio1" class="custom-control-label">Hoạt Động</label>
        </div>
        <div class="custom-control custom-radio">
          <input class="custom-control-input" type="radio" id="customRadio2" name="status" checked=""  value="0">
          <label for="customRadio2" class="custom-control-label">Không Hoạt Động</label>
        </div>
        @error('status')
          <div class="text-danger">{{ $message }}</div>
        @enderror
      </div>
      <div class="form-group">
        <label for="inputSpentBudget">Password<span class="text-danger">(*)</span></label>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
        @error('password')
        			<span class="text-danger">{{ $message }}</span>
        @enderror
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="inputSpentBudget">Nhập Lại Password<span class="text-danger">(*)</span></label>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Nhập lại password" name="password_confirmation">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
      </div>
      <p><i><span class="text-danger">(*)</span> Các Trường Bắt Buộc Phải Nhập</i></p>
      <div class="row">
        <!-- /.col -->
        <div class="col-3">
          <button type="submit" class="btn btn-primary btn-block">Tạo Tài Khoản</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
    <!-- /.form-box -->
</div>
@endsection

resources/views/backend/admins/forgot-password.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Forgot Password</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/dist/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>
      @if (Session::has('status'))
        <p class="text-success">{{ Session::get('status') }}</p>
      @endif
      <form action="{{ route('admin.password.email') }}" method="post">
        @csrf
        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Liên Kết Đặt Lại Mật Khẩu Email</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="{{  route('admin.login') }}">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('backend/admin_lte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('backend/admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/admin_lte/dist/js/adminlte.min.js') }}"></script>
</body>
</html>

resources/views/backend/admins/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Danh Sách Quản Trị Viên')

@section('content')
<div class="row">
	<div class="col-md-3">
		<div class="card card-primary">
	      <!-- form start -->
	      <form method="get" action="{{ route('admin.index') }}">
	        <div class="card-body">
	          	<div class="form-group">
	            	<label for="exampleInputEmail1">Tên Hoặc Email</label>
	            	<input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter">
	          	</div>
	        
	        	<div class="form-group">
		        	 <label for="exampleInputEmail1">Tình Trạng</label>
			        <div class="form-check">
			          <input class="form-check-input" value="1" type="radio" name="active">
			          <label class="form-check-label">Hoạt Động</label>
			        </div>
			        <div class="form-check">
			          <input class="form-check-input" value="0" type="radio" name="active">
			          <label class="form-check-label">Không Hoạt Động</label>
			        </div>
		      </div>
		     </div>
	        <div class="card-footer">
	          <button type="submit" class="btn btn-primary">Tìm Kiếm</button>
	        </div>
	      </form>
	    </div>
	</div>
	<div class="col-md-9">
		<div class="card">
	      <div class="card-header">
	        <h3 class="card-title">Danh Sách Admin</h3>
	      </div>
	      <!-- /.card-header -->
	      <div class="card-body table-responsive p-0" style="height: 500px;">
	        <table class="table table-head-fixed text-nowrap">
	          <thead>
	            <tr>
	              <th>Admin ID</th>
	              <th>Tên</th>
	              <th>Số Điện Thoại</th>
	              <th>Email</th>
	              <th>Quyền</th>
	              <th>Trạng Thái</th>
	            </tr>
	          </thead>
	          <tbody>
	          	
	          	@foreach ($admins as $admin)
	          	@continue(auth('admin')->user()->id == $admin->id)
	            <tr>
	              <td>{{ $admin->id }}</td>
	              <td><a href="{{ route('admin.show', ['id' => $admin->id]) }}">{{ $admin->name }}</a></td>
	              <td>{{ $admin->phone }}</td>
	              <td>{{ $admin->email }}</td>
	              <td>{{ $admin->role->role }}</td>
	              <td>
	              	@if ($admin->active())
	              		Đang Hoạt Động
	              	@else
	              		Không Hoạt Động
	              	@endif
	              </td>
	            </tr>

	            @endforeach
	          	
	          </tbody>
	        </table>
	        <div>
	          {{ $admins->links('pagination::bootstrap-4') }}
	        </div>
	      </div>
	      <!-- /.card-body -->
	    </div>

	</div>
</div>
@endsection

resources/views/backend/admins/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Log in</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/dist/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Admin</b>LTE
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>
      @include('errors.error')
      <form action="{{ route('admin.check-login') }}" method="post">
        @csrf
        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mb-1">
        <a href="{{ route('admin.password.request') }}">I forgot my password</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('backend/admin_lte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('backend/admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/admin_lte/dist/js/adminlte.min.js') }}"></script>
</body>
</html>

resources/views/backend/admins/profile.blade.php
@extends('backend.layouts.master')
@section('title', 'Thông Tin Admin')
@section('content')
	<div class="row">
          <div class="col-md-3">

            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" src="{{ asset('backend/admin_lte/dist/img/user4-128x128.jpg') }}" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{ $admin->name }}</h3>

                <ul class="list-group list-group-unbordered mb-3">
                  <li class="list-group-item">
                    <b>Email</b> <a class="float-right">{{ $admin->email }}</a>
                  </li>
                  <li class="list-group-item">
                    <b>Số Điện Thoại</b> <a class="float-right">{{ $admin->phone }}</a>
                  </li>
                  <li class="list-group-item">
                    @include('errors.error')
                  </li>
                </ul>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Sản Phẩm Đã Thêm</a></li>
            @if (auth('admin')->user()->id == $admin->id || (auth('admin')->user()->role_id == 1 && $admin->role_id != 1))
                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Settings</a></li>
            @endif
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">
                  <div class="tab-pane active" id="activity">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0" style="height: 400px;">
                          <table class="table table-head-fixed text-nowrap">
                            <thead>
                              <tr>
                                <th>Tên Sản Phẩm</th>
                                <th>Giá</th>
                              </tr>
                            </thead>
                            <tbody>
                    @foreach ($admin->products as $product)
                              <tr>
                                <td><a href="{{ route('admin.products.show', ['id' => $product->id ]) }}">{{ $product->name }}</a></td>
                                  <td>{{ $product->price }}</td>
                              </tr>
                    @endforeach
                            </tbody>
                          </table>
                        </div>
                      </div>
                  </div>
                  <div class="tab-pane" id="settings">
                    <form action="{{ route('admin.update', ['id' => $admin->id]) }}" method="post" class="form-horizontal">
                      @csrf
                      @method('put')
                      <div class="form-group row">
                        <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                          <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Email" value="{{ $admin->email }}" disabled>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
                        <div class="col-sm-10">
                          <input type="name" class="form-control" id="inputName" placeholder="Name" value="{{ $admin->name }}">
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="inputEmail" name="email" class="col-sm-2 col-form-label">Số Điện Thoại</label>
                        <div class="col-sm-10">
                          <input type="number" name="phone" class="form-control" id="inputEmail" placeholder="Email" value="{{ $admin->phone }}">
                        </div>
                      </div>
                  @if (auth('admin')->user()->id != $admin->id && auth('admin')->user()->role_id == 1)
                      <div class="form-group row">
                        <label for="inputEmail" name="email" class="col-sm-2 col-form-label">Số Điện Thoại</label>
                        <div class="col-sm-10">
                          <select class="form-control" name="role_id">
                            <option selected="selected" data-select2-id="3" value="{{ $admin->role->id }}">{{ $admin->role->role }}</option>
                    @foreach ($roles as $role)
                      @continue($role->id == 1)
                      @continue($role->id == auth('admin')->user()->role_id)
                                <option value="{{ $role->id }}">{{ $role->role }}</option>
                    @endforeach
                          </select>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="inputEmail" name="email" class="col-sm-2 col-form-label">Có Đang Hoạt Động</label>
                        <div class="col-sm-10">
                          <div class="custom-control custom-radio">
                            <input class="custom-control-input" type="radio" id="customRadio1" name="status" {{ $admin->status ? 'checked' : '' }} value="1">
                            <label for="customRadio1" class="custom-control-label">Hoạt Động</label>
                          </div>
                          <div class="custom-control custom-radio">
                            <input class="custom-control-input" type="radio" {{ $admin->status ? '' : 'checked' }} id="customRadio2" name="status" value="0">
                            <label for="customRadio2" class="custom-control-label">Không Hoạt Động</label>
                          </div>
                        </div>
                      </div>
                  @endif
                      <div class="form-group row">
                        <label for="inputEmail" name="email" class="col-sm-2 col-form-label">Password</label>
                        <div class="col-sm-10">
                          <input type="password" name="password" class="form-control" id="inputEmail" placeholder="Nhập Password">
                        </div>
                  @error('password')
                    <span class="text-danger">{{ $message }}</span>
                  @enderror
                      </div>
                      <div class="form-group row">
                        <label for="inputEmail" name="email" class="col-sm-2 col-form-label">Nhập Lại Password</label>
                        <div class="col-sm-10">
                          <input type="password" name="password_confirmation" class="form-control" id="inputEmail" placeholder="Nhập Lại Password">
                        </div>
                      </div>
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Thay Đổi</button>
                          <a style="float: right;" class="btn btn-danger" href="{{ route('admin.index') }}">Continues</a>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

resources/views/backend/admins/reset-password.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Recover Password</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('backend/admin_lte/dist/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="{{ route('admin.dashboard') }}"><b>Admin</b>LTE</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You are only one step a way from your new password, recover your password now.</p>
      @include('errors.error')
      <form action="{{ route('admin.password.update') }}" method="post">
        @csrf
        <div class="input-group mb-3">
          <input type="hidden" name="email" value="{{ $admin->email }}" class="form-control" placeholder="Email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Mật Khẩu">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
          @error('password')
            <span class="text-danger">{{ $message }}</span>
          @enderror
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password_confirmation" class="form-control" placeholder="Nhập Lại Mật Khẩu">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Đặt Lại Mật Khẩu</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="{{ route('admin.login') }}">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('backend/admin_lte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('backend/admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('backend/admin_lte/dist/js/adminlte.min.js') }}"></script>
</body>
</html>