routes/admin.php
<?php 

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\CategoryController;

// Forgot password
Route::get('admin/forgot-password', [AdminController::class, 'forgotPassword'])->name('admin.password.request');

// Send Mail
Route::post('admin/forgot-password', [AdminController::class, 'sendMail'])->name('admin.password.email');

// Reset Password
Route::get('admin/reset-password', [AdminController::class, 'resetPassword'])->name('admin.password.reset');

Route::post('admin/reset-password', [AdminController::class, 'updatePassword'])->name('admin.password.update');

Route::group(['middleware' => ['auth.admin'],'prefix' => 'admin', 'as' => 'admin.'], function() {
    
    Route::get('/', [ProductController::class, 'index'])->name('dashboard');

    // Get Form Login
    Route::get('login', [AdminController::class, 'login'])->name('login');

    // Check Login
    Route::post('login', [AdminController::class, 'checkLogin'])->name('check-login');

    // Logout
    Route::get('logout', [AdminController::class, 'logout'])->name('logout');


    // Get List Admin
    Route::get('index', [AdminController::class, 'index'])->name('index');

    // Get Form Create a Admin
    Route::get('create', [AdminController::class, 'create'])->name('create')->middleware('super.admin');

    // Add new Admin
    Route::post('store', [AdminController::class, 'store'])->name('store')->middleware('super.admin');

    // Show Admin
    Route::get('show/{id}', [AdminController::class, 'show'])->name('show')->middleware('super.admin');

    // Profile Admin
    Route::get('profile/{id}', [AdminController::class, 'profile'])->name('profile');

    // UpDate Admin
    Route::put('/{id}', [AdminController::class, 'update'])->name('update');

    // Route Orders
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'orders', 'as' => 'orders.'], function() {
        
        Route::get('/', [OrderController::class, 'index'])->name('index');
        Route::get('show/{id}', [OrderController::class, 'show'])->name('show');
        Route::put('update/{id}', [OrderController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [OrderController::class, 'destroy'])->name('destroy');

        // Get Form Order By Date
        Route::get('order-by-date', [OrderController::class, 'orderByDate'])->name('order-by-date');

        // Get List Order By Date
        Route::get('search-order-by-date', [OrderController::class, 'searchOrderByDate'])->name('search-order-by-date');

        // Get Credit Report
        Route::get('credit', [ReportController::class, 'creditReport'])->name('credit');

        // Get Summary Report
        Route::get('summary', [ReportController::class, 'summaryReport'])->name('summary');

        // Get Pending Order
        Route::get('pending', [OrderController::class, 'pendingOrder'])->name('pending');

        
    });

    // Route Users
    Route::group(['middleware' => ['direct.admin'], 'prefix' => 'users', 'as' => 'users.'], function() {

        // Get List Users
        Route::get('/', [UserController::class, 'index'])->name('index');

        // Get Profile
        Route::get('show/{id}', [UserController::class, 'show'])->name('show');

        // Get Form User By Date
        Route::get('user-by-date', [UserController::class, 'userByDate'])->name('user-by-date');

        // Get List Order By Date
        Route::get('search-user-by-date', [UserController::class, 'searchUserByDate'])->name('search-user-by-date');
    });

    // Route Category
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {

        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('create', [CategoryController::class, 'create'])->name('create');
        Route::post('/', [CategoryController::class, 'store'])->name('store');
        Route::get('show/{id}', [CategoryController::class, 'show'])->name('show');
        Route::get('edit/{id}', [CategoryController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [CategoryController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');   
    });

    // Route Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function() {

        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('create', [ProductController::class, 'create'])->name('create');
        Route::post('/', [ProductController::class, 'store'])->name('store');
        Route::get('show/{id}', [ProductController::class, 'show'])->name('show');
        Route::get('edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::put('update/{id}', [ProductController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [ProductController::class, 'destroy'])->name('destroy');

        // Route::get('delete/{id}', function($id) {
        //     return redirect(route('admin.products.show', $id))->with('error', 'Sản Phẩm Hiện Đang Có Đơn Hàng');
        // });
    });
});

routes/web.php
<?php

use App\Http\Controllers\CartDemoController;
use App\Http\Controllers\ProductDemoController;
use App\Http\Controllers\SessionDemoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

require __DIR__.'/admin.php';

/**
 * Route For Session Demo
 */
Route::group(['prefix' => 'session-demo', 'as' => 'session-demo.'], function () {
    // URL này để hiển thị tất cả data đang có trong SESSION
    Route::get('/', [SessionDemoController::class, 'index'])->name('index');

    // URL này để thêm mới 1 sản phẩm vào Giỏ Hàng
    Route::post('/', [SessionDemoController::class, 'store'])->name('store');

    // URL này để update quantity của 1 sản phẩm đã có trong Giỏ Hàng
    Route::put('/{id}', [SessionDemoController::class, 'update'])->name('update');

    // URL này để xoá 1 sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/{id}', [SessionDemoController::class, 'destroy'])->name('destroy');

    // URL này để xoá tất cả sản phẩm ra khỏi Giỏ Hàng
    Route::delete('/all', [SessionDemoController::class, 'destroyAll'])->name('destroyAll');
});

// Route for Product Demo
Route::get('product-demo', [ProductDemoController::class, 'index'])->name('product-demo.index')->middleware('guest');
Route::get('product-demo/create', [ProductDemoController::class, 'create'])->name('product-demo.create')->middleware('guest');
Route::post('product-demo', [ProductDemoController::class, 'store'])->name('product-demo.store')->middleware('guest');

// Route for Cart Demo
Route::group(['prefix' => 'cart-demo', 'as' => 'cart-demo.', 'middleware' => 'guest'], function () {
    Route::get('/', [CartDemoController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartDemoController::class, 'addCart'])->name('add-cart');
    Route::put('/{id}/update-quantity', [CartDemoController::class, 'updateQuantity'])->name('update-quantity');
    Route::delete('/{id}/remove-product-in-cart', [CartDemoController::class, 'removeProductInCart'])->name('remove-product-in-cart');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $fillable = [
        'user_id',
        'name',
        'phone',
        'address',
        'status',
        'comment',
    ];

    public function orderDetails()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Models\Order;
use App\Models\Category;
use App\Models\Brand;
use App\Models\OrderDetail;
use App\Util\OrderCommon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    function __construct(Order $order, OrderDetail $orderDetail)
    {
        $this->order = $order;
        $this->orderDetail = $orderDetail;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data   = [];

        $orders = $this->order->with('user')->with('orderDetails');

        // Check if have search Order ID
        if (!empty($request->get('order_number'))) {
            $orders->where('id' , $request->get('order_number'));
        }

        // Check if have search Customer ID
        if (!empty($request->get('customer_id'))) {
            $orders->where('user_id' , $request->get('customer_id'));
        }
        
        // Check if have search Name
        if (!empty($request->get('name'))) {
            $orders->where('name' , 'like', '%'.$request->get('name').'%');
        }
        
        // Check if have search Phone
        if (!empty($request->get('phone'))) {
            $orders->where('phone' , $request->get('phone'));
        }
        
        // Check if have search Customer ID
        if (!empty($request->get('address'))) {
            $orders->where('address' , $request->get('address'));
        }
        
        // Lấy list order
        $orders         = $orders->orderBy('created_at', 'desc')->paginate(10);

        $data['orders'] = $orders;
        return view('backend.orders.index', $data);
    }

    public function orderByDate()
    {
        $data = [];

        $year = Carbon::now()->year;

        $data['year'] = $year;
        return view('backend.orders.order_by_date', $data);
    }

    public function searchOrderByDate(Request $request)
    {

        $day   = $request->get('day');
        $month = $request->get('month');
        $year  = $request->get('year');

        $orders = $this->order->with('user')->with('orderDetails');

        $orders->whereYear('created_at', $year);

        $status = 'year';
        if (!empty($month)) {

            $orders->whereMonth('created_at', $month);
            $status = 'month';

            if (!empty($day)) {
                $orders->whereDay('created_at', $day);
                $status = 'day';
            }
        }
        
        $orders = $orders->orderBy('created_at', 'asc')->get();

        if ($status == 'year') {
            $day['year'] = $year;

            $result = OrderCommon::calculate($orders, $day, 'mon');

            $orders = $result;
        }

        if ($status == 'month') {
            $day['year']  = $year;
            $day['month'] = $month;

            $result = OrderCommon::calculate($orders, $day, 'mday');

            $orders = $result;
        }

        $date = [];
        if ($status == 'day') {
            $date['year']  = $year;
            $date['month'] = $month;
            $date['day']   = $day;

            $data['date'] = $date; 
        }
        // dd($orders);

        $data['orders'] = $orders;
        $data['status'] = $status; 

        return view('backend.orders.search_order_by_day', $data);
    }

    public function pendingOrder()
    {
        $data   = [];
        
        $orders = $this->order->with('orderDetails')
                    ->where('status', 1)
                    ->get();

        $data['orders'] = $orders;

        return view('backend.orders.pending_order', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [];

        // Get orders
        $order = $this->order
                ->with('orderDetails')
                ->with('user')
                ->findOrFail($id);

        // Get Order Detail
        $orderDetails = OrderDetail::with('product')->where('order_id', $order->id)->get();
        
        $data['order']        = $order;
        $data['orderDetails'] = $orderDetails;
        return view('backend.orders.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order         = $this->order->findOrFail($id);

        $order->status = $request->status;

        try {
            $order->save();

            return back()->with('success', 'Cập Nhật Đơn Hàng Thành Công');
        } catch (Exception $e) {
            return back()->with('err', 'Cập Nhật Đơn Hàng Không Thành Công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = $this->order->findOrFail($id);

        try {
            // Delete data
            $order->delete();

            // Success
            return back()
                ->with('success', 'Xóa Đơn Hàng Thành Công');
        } catch (\Exception $ex) {
            return back()
                ->with('error', $ex->getMessage());
        }
    }
}

resources/views/backend/orders/_day.blade.php
@if (!empty($orders->all()))
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{{ $date['day'] }} /
          <a href="{{ route('admin.orders.search-order-by-date', ['month' => $date['month'], 'year' => $date['year']]) }}">{{ $date['month'] }}</a> /
          <a href="{{ route('admin.orders.search-order-by-date', ['year' => $date['year']]) }}">{{ $date['year'] }}</a></h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0" style="height: 400px;">
        <table class="table table-head-fixed text-nowrap">
          <thead>
            <tr>
              <th>Số Đơn Hàng</th>
              <th>Tên Khách Hàng</th>
              <th>Số Điện Thoại</th>
              <th>Địa Chỉ</th>
            </tr>
          </thead>
          <tbody>
          	@foreach ($orders as $order)

            <tr>
              <td><a href="{{ route('admin.orders.show', ['id' => $order->id ]) }}">{{ $order->id }}</a></td>
              <td>{{ $order->name }}</td>
              <td>{{ $order->phone }}</td>
              <td>{{ $order->address }}</td>
            </tr>

            @endforeach
          	
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
@endif

resources/views/backend/orders/_month.blade.php
<div class="card">
  <div class="card-header">
    <h3 class="card-title">{{ $orders['month'] }} /
      <a href="{{ route('admin.orders.search-order-by-date', ['year' => $orders['year']]) }}">{{ $orders['year'] }}</a>
    </h3>
  </div>
</div>
<div class="row">

  @foreach ($orders as $day => $value)
    @continue($day == 'year')
    @continue($day == 'month')

  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>Số Đơn Hàng: {{ $value['quantity'] }}</h3>

        <p>Tổng Số Tiền: {{ number_format($value['price']) }}</p>
      </div>
      <div class="icon">
        <i class="ion ion-bag">{{ $day }}</i>
      </div>
      <a href="{{ route('admin.orders.search-order-by-date', ['day' => $day, 'month' => $orders['month'], 'year' => $orders['year']]) }}" class="small-box-footer">Thêm Thông Tin <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>

  @endforeach

</div>

resources/views/backend/orders/_year.blade.php
<div class="card">
  <div class="card-header">
    <h3 class="card-title">{{ $orders['year'] }}</h3>
  </div>
</div>

<div class="row">
  
  @foreach ($orders as $month => $value)
    @continue($month == 'year')

  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>Số Đơn Hàng: {{ $value['quantity'] }}</h3>

        <p>Tổng Số Tiền: {{ number_format($value['price']) }}</p>
      </div>
      <div class="icon">
        <i class="ion ion-bag">{{ $month }}</i>
      </div>
      <a href="{{ route('admin.orders.search-order-by-date', ['month' => $month, 'year' => $orders['year']]) }}" class="small-box-footer">Thêm Thông Tin <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>

  @endforeach

</div>

resources/views/backend/orders/detail.blade.php
@extends('backend.layouts.master')

@section('title', 'Chi Tiết Đơn Hàng')

@section('content')
	@if (!empty($order->orderDetails))
	
	<div class="invoice p-3 mb-3">
      <!-- title row -->
      <div class="row">
        <div class="col-12">
          <h4>
            <i class="fas fa-globe"></i> AdminLTE, Inc.
            <small class="float-right">Ngày Tạo Đơn: {{ $order->created_at }}</small>
          </h4>
        </div>
        <!-- /.col -->
      </div>
      <!-- info row -->
      <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
          Từ
          <address>
            <strong>Admin, Inc.</strong><br>
            Địa Chỉ: 795 Folsom Ave, Suite 600<br>
            San Francisco, CA 94107<br>
            Số Điện Thoại: (804) 123-5432<br>
            Email: info@almasaeedstudio.com
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          To
          <address>
            <strong>
              @if (!empty($order->user))
              <a href="{{ route('admin.users.show', ['id' => $order->user->id]) }}">{{ $order->name }}</a>
              @else
              {{ $order->name }}
              @endif

            </strong><br>
            Địa Chỉ: {{ $order->address }}<br>
            Số Điện Thoại: {{ $order->phone }}<br>
            Email: @if (!empty($order->user))
            	{{ $order->user->email }}
            	@else
            		0
            	@endif
          </address>
        </div>
        <!-- /.col -->
        <div class="col-sm-4 invoice-col">
          <b>Số Đơn Hàng:</b> {{ $order->id }}<br>
          <b>Tài Khoản:</b> 
            @if (!empty($order->user))
              	{{ $order->user->id }}
          	@else
              		0
          	@endif <br>

          <b>Tình Trạng Đơn Hàng:</b>
            @if ($order->status == 1)
                Chưa Xử Lý
            @elseif ($order->status == 2)
                Đang Giao Hàng
            @elseif ($order->status == 3)
                Đã Giao Thành Công
            @else
                Đã Hủy
            @endif
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      <!-- Table row -->
      <div class="row">
        <div class="col-12 table-responsive">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Số Lượng</th>
              <th>Tên Sản Phẩm</th>
              <th>Mô Tả</th>
              <th>Giá Bán</th>
              <th>Tổng</th>
            </tr>
            </thead>
            <tbody>
            	@php
            		$total = 0;
            	@endphp
            @foreach ($orderDetails as $orderDetail)
            	@php
            		$subTotal = $orderDetail->quantity * $orderDetail->price;
            		$total += $subTotal;

            		$price = $orderDetail->price;

            	@endphp
            <tr>
              <td>{{ $orderDetail->quantity }}</td>
              <td><a href="{{ route('admin.products.show', ['id' => $orderDetail->product->id]) }}" target = "_ blank">{{ $orderDetail->product->name }}</a></td>
              <td>{{ $orderDetail->product->content }}</td>
              <td>{{ number_format($price) }}</td>
              <td>{{ number_format($subTotal) }}</td>
            </tr>

            @endforeach

            </tbody>
            <tfoot> 
              <tr>
                <th colspan="4">Vận Chuyển:</th>
                <td>0</td>
              </tr>
              <tr>
                <th colspan="4">Tổng Số Tiền:</th>
                <td>{{ number_format($total) }}</td>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- /.row -->
    </div>

	@endif
@endsection

resources/views/backend/orders/index.blade.php
@extends('backend.layouts.master')

@section('title', 'Danh Sách Đơn Hàng')

@section('content')
<div class="row">

<div class="col-md-3">
	<div class="card card-primary">
      <!-- form start -->
      <form method="get" action="{{ route('admin.orders.index') }}">
        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputEmail1">Số Đơn Hàng</label>
            <input type="number" name="order_number" value="{{ request()->get('order_number') }}" class="form-control" id="exampleInputEmail1" placeholder="Enter Order Number">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">ID Khách Hàng</label>
            <input type="number" name="customer_id" value="{{ request()->get('customer_id') }}" class="form-control" id="exampleInputEmail1" placeholder="Enter Customer ID">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Tên</label>
            <input type="text" name="name" value="{{ request()->get('name') }}" class="form-control" id="exampleInputEmail1" placeholder="Enter Name">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Số Điện Thoại</label>
            <input type="text" name="phone" value="{{ request()->get('phone') }}" class="form-control" id="exampleInputEmail1" placeholder="Enter Phone">
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Địa Chỉ</label>
            <input type="text" name="address" value="{{ request()->get('address') }}" class="form-control" id="exampleInputEmail1" placeholder="Enter Address">
          </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Tìm Kiếm</button>
          <a style="float: right;" class="btn btn-primary" href="{{ route('admin.orders.index') }}">Xóa Bộ Lọc</a>
        </div>
      </form>
    </div>
</div>

<div class="col-md-9">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Danh Sách Các Đơn Hàng</h3>
        <br>
        @include('errors.error')
      </div>
      
      @if (!empty($orders->all()))
      <!-- /.card-header -->
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th>Tên Khách Hàng</th>
              <th>Tổng Số Lượng</th>
              <th>Tổng Tiền</th>
              <th>Trạng Thái</th>
              <th>Thao Tác</th>
            </tr>
          </thead>
          <tbody>
          	
          	@foreach ($orders as $order)

            <tr>
              <td>{{ $order->name }}</td>
              @php
                $price    = 0;
                $quantity = 0;
              @endphp
              @foreach ($order->orderDetails as $orderDetail)
                @php
                  $quantity += $orderDetail->quantity;
                  $price    += $orderDetail->quantity*$orderDetail->price;
                @endphp
                
              @endforeach
              <td>{{ $quantity }}</td>
              <td>{{ number_format($price) }} đ</td>
              <form action="{{ route('admin.orders.update', ['id' => $order->id]) }}" method="post">
                @csrf
                @method('put')
              <td>
                <select class="form-control select2 select2-hidden-accessible" name="status" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
                  <option selected="selected" data-select2-id="3" value="{{ $order->status }}">
                    @if ($order->status == 1)
                        Chưa Xử Lý
                    @elseif ($order->status == 2)
                        Đang Giao Hàng
                    @elseif ($order->status == 3)
                        Đã Giao Thành Công
                    @else
                        Đã Hủy
                    @endif
                  </option>
                  @for ($i = 1; $i <= 4 ; $i++)
                    @continue($order->status == $i)
                    <option value="{{ $i }}">
                      @if ($i == 1)
                          Chưa Xử Lý
                      @elseif ($i == 2)
                          Đang Giao Hàng
                      @elseif ($i == 3)
                          Đã Giao Thành Công
                      @else
                          Đã Hủy
                      @endif
                    </option>
                  @endfor
                </select> 
              </td>
              <td>
                <a href="{{ route('admin.orders.show', ['id' => $order->id ]) }}" class="btn btn-info" target = "_ blank">Chi tiết</a>|
                <button type="submit" class="btn btn-primary"
                  {{$order->status == 1 || $order->status == 2 ? '' : 'disabled'}}
                >Cập Nhật</button>
                </form>

                <br>
                
                <form action="{{ route('admin.orders.destroy', $order->id ) }}" method="post">
                  @csrf
                  @method('delete')
                  <button type="submit" class="btn btn-danger"
                  {{$order->status == 1 ? '' : 'disabled'}}>Xóa</button>
                </form>
                
              </td>
              

              
            </tr>

            @endforeach
          	
          </tbody>
        </table>
        <div>
          {{ $orders->links('pagination::bootstrap-4') }}
        </div>
      </div>
      <!-- /.card-body -->
      @else
    <p>Không có đơn hàng</p>
    @endif
    </div>
    
  </div>
</div>
@endsection

resources/views/backend/orders/pending_order.blade.php
@extends('backend.layouts.master')

@section('title', 'Tất Cả Đơn Hàng Chưa Xử Lý')

@section('content')

@if (!empty($orders))
	<div class="card">
      <div class="card-header">
        <h3 class="card-title">Danh Sách Đơn Hàng Chưa Xử Lý</h3>
        <br>
        @include('errors.error')
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0" style="height: 400px;">
        <table class="table">
          <thead>
            <tr>
              <th>Tên Khách Hàng</th>
              <th>Tổng Số Lượng</th>
              <th>Tổng Tiền</th>
              <th>Trạng Thái</th>
              <th>Thao Tác</th>
            </tr>
          </thead>
          <tbody>
            
            @foreach ($orders as $order)

            <tr>
              <td>{{ $order->name }}</td>
              @php
                $price    = 0;
                $quantity = 0;
              @endphp
              @foreach ($order->orderDetails as $orderDetail)
                @php
                  $quantity += $orderDetail->quantity;
                  $price    += $orderDetail->quantity*$orderDetail->price;
                @endphp
                
              @endforeach
              <td>{{ $quantity }}</td>
              <td>{{ number_format($price) }} đ</td>
              <form action="{{ route('admin.orders.update', ['id' => $order->id]) }}" method="post">
                @csrf
                @method('put')
              <td>
                <select class="form-control select2 select2-hidden-accessible" name="status" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
                  <option selected="selected" data-select2-id="3" value="{{ $order->status }}">
                    @if ($order->status == 1)
                        Chưa Xử Lý
                    @elseif ($order->status == 2)
                        Đang Giao Hàng
                    @elseif ($order->status == 3)
                        Đã Giao Thành Công
                    @else
                        Đã Hủy
                    @endif
                  </option>
                  @for ($i = 1; $i <= 4 ; $i++)
                    @continue($order->status == $i)
                    <option value="{{ $i }}">
                      @if ($i == 1)
                          Chưa Xử Lý
                      @elseif ($i == 2)
                          Đang Giao Hàng
                      @elseif ($i == 3)
                          Đã Giao Thành Công
                      @else
                          Đã Hủy
                      @endif
                    </option>
                  @endfor
                </select> 
              </td>
              <td>
                <a href="{{ route('admin.orders.show', ['id' => $order->id ]) }}" class="btn btn-info" target = "_ blank">Chi tiết</a>|
                <button type="submit" class="btn btn-primary"
                  {{$order->status == 1 || $order->status == 2 ? '' : 'disabled'}}
                >Cập Nhật</button>
                </form>
                <br>
                <form action="{{ route('admin.orders.destroy', $order->id ) }}" method="post">
                  @csrf
                  @method('delete')
                  <button type="submit" class="btn btn-danger"
                  {{$order->status == 1 || $order->status == 2 ? '' : 'disabled'}}>Xóa</button>
                </form>
                
              </td>
              

              
            </tr>

            @endforeach
            
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
@else
  <p>Không Có Đơn Hàng</p>
@endif

@endsection

resources/views/backend/orders/search_order_by_day.blade.php
@extends('backend.layouts.master')

@section('title', 'Tìm Kiếm Đơn Hàng Theo Ngày')

@section('content')
	@if ($status === 'year')

		@include('backend.orders._year')

	@elseif ($status === 'month')

		@include('backend.orders._month')

	@elseif ($status === 'day')

		@include('backend.orders._day')

	@endif
@endsection